# Generated by Django 2.1.3 on 2018-11-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_userpref_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'like'), ('d', 'dislike'), ('U', 'undecided')], max_length=2),
        ),
    ]
